<br /><h4>   
NO INTRODUZCA AQUÍ EL CÓDIGO DE SU APLICACIÓN PORQUE EL CONTENIDO DE ESTE<br />
ARCHIVO SE CREARÁ DE MANERA AUTOMÁTICA CUANDO SE GENERE LA APLICACIÓN Y SE<br />
ELIMINARÁ CUALQUIER MODIFICACIÓN QUE CONTENGA.<br />
<br />
EN LAS PROPIEDADES DEL PROYECTO PUEDE INDICAR CUAL SERÁ LA PÁGINA DE INICIO<br />
DE SU APLICACIÓN.</h4>
